### ISSUE TITLE
bind-9.19.24  run issue as segfault error.

### ISSUE THREAD

**Issue by myld3416** [getnamingo/fossbilling-dns#10]
I'm on:

1.  bind-9.19.24
2.  Linux centos7-9 3.10.0-1160.71.1.el7.x86_64
3.  cpu: 12core
4. memory: 64G

I have a error message below in /var/log/messages.log :

message.log:

```
Aug18 04:38:10 dns01 kernel:isc-1oop-0034[14137]:segfault at 9f ip 00007fccd60365d8 sp 00007fcc6aff3d90 error 6 in libns-9.19.24.so [7Ecc6028000+17E000)*
Aug 18 04:38:10 dns01 abrt-hookccpp: Process 14102 (named)of user 53 killed by $rGseGv - dumping core
Aug18 04:38:14 dns01 systemd:named.service:main process exited, code-killed, status=11/$EGV
Aug18 04:38:14 dns01systemd:Unit named.service entered failed state.18Aug04:38:14 dns01systemd:named.service failed.18Aug04:38:14 dns01abrt-server: Executable '/opt/named/sbin/named' doesn't belong to any package and processUnpackaged is set to "no
Aug18 04:38:14 dns01 abrt-server;'post-create"on"/var/spool/abrt/ccpp-2024-08-18-04:38:10-14102'exited with 1
Aug1804:38:14 dns01 abrt-server: Deleting problem directory"/var/spool/abrt/ccpp-2024-08-18-04:38:10-14102'

```
**it's segfault at 9f ip 00007fccd60365d8 sp 00007fcc6aff3d90 error 6 in libns-9.19.24.s0**

I don't konw it's like memory leak or bind9 bugs.

but I don't find any CVE message. 

please help me.

**Comment by getpinga** [comment]
Hello,
Unfortunately I'm not sure how is connected with the project, but just in case will try to replicate it and report here.

**Comment by getpinga** [comment]
Hello,
Unfortunately I cound not replicate and it is not related to the tool, so I'm closing it. If you find new issues, please report again.
