### ISSUE TITLE
Errors when placing order and/or activating

### ISSUE THREAD

**Issue by amanzella** [getnamingo/fossbilling-dns#5]
I have set the product, selected PowerDNS, set the API IP, Key and etc. When I try to order or activate the order, it just spins. After checking, I'm getting a 500 error on /api/admin/order/activate?id=

This only happens when trying to order/activate the DNS product. Everything else works fine.

**Comment by getpinga** [comment]
Please download the new https://github.com/getnamingo/fossbilling-dns/blob/main/Servicedns/Providers/PowerDNS.php I just uploaded and try again.

If still having issues, send me the last few lines of the `/data/log/php_error.log` to see what happens.

**Comment by amanzella** [comment]
@getpinga I have fixed the issue and issued a pull request. I have not worked on the delete error yet, but I plan to work on it soon. 

#6

**Comment by amanzella** [comment]
@getpinga I corrected the delete error and also add the ability to delete the order if the zone is not found in powerdns. It's been committed to pull request #6 as well.

**Comment by getpinga** [comment]
Thanks a lot, fixed a bit the formatting and approved it.

**Comment by getpinga** [comment]
I'll ask the other users that had the issue to test and then will close the ticket.

**Comment by getpinga** [comment]
Seems working. If someone has the same or similar issue, please open a new ticket to investigate.
