### ISSUE TITLE
bind9 issue

### ISSUE THREAD

**Issue by dominic16y** [getnamingo/fossbilling-dns#9]
Hi everyone:
when I use bind9 as DNS server with fossbilling-dns 
fossbilling-dns  will create zone file at /var/lib/bind 

how do I automatic load those zone file at named.conf configuration? 
or there is no way about auto load zone file 
you have to load them by manual?

**Comment by getpinga** [comment]
Hello,
Investigating, will report here.

**Comment by getpinga** [comment]
Hello,
Please update to 1.0.0-RC1. We have updated the way how BIND works and now it requires API access and edits the named.conf and reloads the zones. I consider this ticket fixed but once you test and if you experience new issues, please report again. Thank you.
